# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/BEV_detection.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/BEV_detections_list.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/BEV_tracker.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/BEV_trackers_list.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Bounding_Box_2D.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Bounding_Box_2D_list.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Bounding_Box_3D.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Bounding_Box_3D_list.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/GT_3D_Object.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/GT_3D_Object_list.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Obstacle.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Obstacles_list.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/CarControl.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Node.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Way.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Lane.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/MonitorizedLanes.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/MonitorizedRegElem.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/RegulatoryElement.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Landmark.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/DM_path.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/DM_pose.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/DM_posestamped.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Location.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Rotation.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Traffic_Sign.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Traffic_Sign_List.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Transform.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Waypoint.msg;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg/Path.msg"
services_str = ""
pkg_name = "t4ac_msgs"
dependencies_str = "std_msgs;geometry_msgs;vision_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "t4ac_msgs;/home/robesafe/t4ac_ws/src/t4ac_architecture/t4ac_config_layer/t4ac_msgs_ros/msg;std_msgs;/opt/ros/melodic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/melodic/share/geometry_msgs/cmake/../msg;vision_msgs;/opt/ros/melodic/share/vision_msgs/cmake/../msg;sensor_msgs;/opt/ros/melodic/share/sensor_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
